# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c
xcode_workspace: Example/Gears.xcworkspace
xcode_scheme: GearsSampleApp
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
podfile: Example/Podfile

script:
- set -o pipefail && xcodebuild -workspace Example/Gears.xcworkspace -scheme GearsSampleApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint